### ISSUE TITLE
minibuffer doesn't expand

### ISSUE THREAD

**Issue by Xunius** [SavchenkoValeriy/emacs-powerthesaurus#10]
Hi,
I noticed that when issuing `M-x powerthesaurus-lookup-word` when a word is selected, my minibuffer won't expand to show the candidates as illustrated in the demo gif, but only showing the `choose a synonym` prompt. I have to type `?` to manually expand it. How could I let it auto expand? Thanks.

**Comment by SavchenkoValeriy** [comment]
Hi,
can you please attach a screenshot of such behavior?

**Comment by Xunius** [comment]
![Screenshot from 2020-02-28 17-31-48](https://user-images.githubusercontent.com/8076931/75535915-49303100-5a50-11ea-8f1b-129198302010.png)
Hi, thanks for the prompt reply.
This is how it looks like after I do `M-x powerthesaurus-lookup-word-at-point`.
I noticed that both `?` and `TAB` will trigger the completion list. So maybe that's the expected behavior and I just did not see that in the demo gif. I'm perfectly fine with the `TAB` trigger. Can consider close this.

**Comment by SavchenkoValeriy** [comment]
What completion system do you use? I guess that if it's not Helm or Ivy, it would indeed look like this

**Comment by Xunius** [comment]
I was not using Helm nor Ivy.

**Comment by SavchenkoValeriy** [comment]
Yeah, I use whatever completion system is currently set up by the user. The default one doesn't show candidates (without TAB) for anything (files, buffers, functions, etc.).
I'm glad we resolved it :)
