### ISSUE TITLE
Is this package broken now?

### ISSUE THREAD

**Issue by hongyi-zhao** [SavchenkoValeriy/emacs-powerthesaurus#16]
On Ubuntu 20.04, I tried to use this package, but it didn't work.

![image](https://user-images.githubusercontent.com/11155854/126865198-ea2743df-1024-4d18-86a4-f77098380022.png)

As you can see above, `M-x powerthesaurus-lookup-word RET` command returned nothing.

Any hints for this problem?

Regards,
HY

**Comment by maxchaos** [comment]
Hi there. I don't see any issues on my current installation. Are you sure you are running this correctly?
The command `powerthesaurus-lookup-word` asks for the word to find synonyms for in the minibuffer whereas the command `powerthesaurus-lookup-word-at-point` will look for synonyms for the word where the cursor is located.

**Comment by hongyi-zhao** [comment]
I also tried with `M-x powerthesaurus-lookup-word-at-point RET`, but obtain the same result:

![image](https://user-images.githubusercontent.com/11155854/126866219-0c11d8f2-eec3-497d-9711-361e4a369ef8.png)

**Comment by maxchaos** [comment]
That's strange. Can you try the following and tell me if that works for you (no need to post a screenshot):
1. Run `M-x powerthesaurus-lookup-word`
2. At the minibuffer's prompt, type the word `you` and, finally, press enter.

Also, mind telling me if you installed this package from source or from MELPA?

**Comment by hongyi-zhao** [comment]
> That's strange. Can you try the following a couple of times and tell me if that works for you (no need to post a screenshot):
> 
>     1. Run `M-x powerthesaurus-lookup-word`
> 
>     2. At the minibuffer's prompt, type the word `you` and, finally, press enter.
 
I tried it 3 times and all the results were the same as previously reported.

> Also, mind telling me if you installed this package from source or from MELPA?

In my situation, `emacs-powerthesaurus` is installed by [straight.el](https://github.com/raxod502/straight.el), which has the capability of [integration-with-use-package](https://github.com/raxod502/straight.el#integration-with-use-package), and automatically use the upstream git master version. See below for the version info retrieved and managed by straight.el:

```
$ git log -1
commit 93036d3b111925ebc34f747ff846cb0b8669b92e (HEAD -> master, origin/master, origin/HEAD)
Merge: 81a262e dd9037f
Author: Panagiotis Vlantis <panagiotis.vlantis.mtc@windowslive.com>
Date:   Mon Jul 20 18:46:37 2020 +0300

    Merge pull request #12 from maxchaos/master
    
    Fix powerthesaurus.org interface
```

**Comment by lachlanA** [comment]
Yes,  I'm seeing the same problem,   on Debian 9,  with 27.2. GNU Emacs 27.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)  of 2021-03-27

**Comment by maxchaos** [comment]
Hmm. Can you please check if this is an issue with retrieving data from the website? You should be able to do so by setting `request` to log everything (e.g., by pressing `M-:`, entering `(powerthesaurus-debug-connection)` and hitting enter) and then repeating the steps above. When this process is finished, there should be a hidden buffer named ` *request-log*` (there is a space at the beginning of the buffer's name) which should contain the logs in question.

**Comment by hongyi-zhao** [comment]
See [here](https://github.com/hongyi-zhao/temp/blob/master/emacs/request-log) for more detailed info.

**Comment by duckwork** [comment]
I have the same issue using powerthesaurus.el on Windows 10 with Emacs 27.2 and powerthesaurus 0.1.0 (latest commit dd9037f).  The log I got (which was in *Messages* for some reason) is here: https://ttm.sh/eEd.txt

**Comment by ntrocado** [comment]
Same issue here. GNU Emacs 28.1 (build 52, x86_64-w64-mingw32) of 2022-04-04

**Comment by duckwork** [comment]
For everyone else on this thread, I've found that [dictionary.el](https://github.com/myrkr/dictionary-el), which queries dict.org and other dictionaries, including the moby thesaurus, is fairly useful for synonym lookups.

**Comment by hongyi-zhao** [comment]
@duckwork Have you confirmed that the package is running smoothly?

**Comment by duckwork** [comment]
@hongyi-zhao this package? no, I don't use it. the dictionary.el I linked in my comment works for me though.

**Comment by maxchaos** [comment]
@ntrocado unfortunately the repositories of my distribution do not provide Emacs 28 yet so I cannot test whether it is a compatibility issue with the new version in general or in combination with mingw. This means that I'll have to set up a podman image for testing as soon as I find some time. Are the symptoms you experience exactly the same as the ones of the issue's original author? That would be strange because the internals of this package have been rewritten quite a bit since then.

**Comment by ntrocado** [comment]
@maxchaos They are the same symptoms as far as I can tell.
I installed via `straight-use-package`. `M-x` `powerthesaurus-lookup-word` enter `you` enter, and the minibuffer shows:
```
(1/0) Choose a candidate: 
```
Here's my [` *request log*`](https://1drv.ms/t/s!AqyNKbUaOh_4g_9dtuuJeWoG_8_aQA?e=sXs6Q8).

**Comment by duckwork** [comment]
Yes

**Comment by hongyi-zhao** [comment]
What's your configuration? It seems this package doesn't exist on [melpa](https://melpa.org/#/).

**Comment by maxchaos** [comment]
@ntrocado this package seems to work as expected with Emacs version 28.1 running inside an Ubuntu based container so I'll need more to go on. 

Firstly, can you tell me the exact version of the powerthesaurus package you are using (it should be written in the comments section of the elisp module, which you can visit by running `M-x find-library RET powerthesaurus RET`).

Secondly, do you have `curl` installed on your system and, if so, does it support compression? Taking a quick look at the log you uploaded, either Emacs failed to uncompress the response or there is some kind of encoding issue since the text following the headers is unreadable. In order to check if you version of 'curl' supports encoding, you can run the following in the terminal and check if `libz` is mentioned among the features.

**Comment by ntrocado** [comment]
@maxchaos I'm using version 0.2.1. `curl -V` prints `libz` among the features.

There's definitively some kind of encoding issue.... In fact, I solved the problem by adding this to my init file:
```
(setq powerthesaurus-request-headers
	(delete '("Accept-Encoding" . "gzip, deflate, br")
		powerthesaurus-request-headers))
```

Unless you have further suggestions that can also be useful for others, as far as I'm concerned feel free to close the issue... Thanks!
