### ISSUE TITLE
Powerthesaurus Listing Only One Term

### ISSUE THREAD

**Issue by nasanos** [SavchenkoValeriy/emacs-powerthesaurus#17]
Recently (as in just yesterday), the terms list from Powerthesaurus started being abbreviated down to just one term. It had been working fine for me up until then.

It may be a local issue. However, outside of Emacs, I'm working with another program that gets synonyms from Powerthesaurus, and it has continued to work as expected. I tried changing the `User-Agent` header, but that didn't seem to have any effect.

Here, for example, is what I get on the word `examples` (I'm using Helm for completions):
![emacs-powerthesaurus-issue](https://user-images.githubusercontent.com/19861991/142665894-f52d3248-9d0b-4f50-8960-11de86c96f3f.png)

**Comment by marlinstrub** [comment]
I can confirm this issue. Started for me yesterday evening.

**Comment by n14s** [comment]
Experiencing the same.

**Comment by maxchaos** [comment]
Hi! Thanks for reporting. The latest version (0.2.0) should be addressing this issue. Let me know if problem persists.

**Comment by danielfleischer** [comment]
The issue is fixed for me; being able to look at antonyms, definitions and sentences is a very nice addition. Thank you very much for this wonderful package!

**Comment by marlinstrub** [comment]
The issue is fixed for me too. Thank you very much for fixing and extending this package, it really is superb!

The only nitpick I have is that the synonyms now seem to be ordered on their length instead of their rating. Is this intentional?

**Comment by danielfleischer** [comment]
I don't experience it, using Helm. Maybe it's your completion framework.

**Comment by marlinstrub** [comment]
Good to know, thanks @danielfleischer

**Comment by marlinstrub** [comment]
Yep, seems to be an issue with vertico.

**Comment by maxchaos** [comment]
@marlinstrub Could you check if you experience the same ordering issue with the latest commit?

**Comment by marlinstrub** [comment]
@maxchaos Nope, the issue is gone with the latest commit. Thanks a lot!
