### ISSUE TITLE
Error when initing emacs

### ISSUE THREAD

**Issue by nbarrientos** [SavchenkoValeriy/emacs-powerthesaurus#32]
Hi,

Thanks for this package :)

Since `20230320.2121`, I get this error message in the `*Warnings*` buffer when I start Emacs:

```
Error (use-package): powerthesaurus/:catch: Symbol’s value as variable is void: powerthesaurus-transient Disable showing Disable logging
```

This is how I configure the package:

```emacs-lisp
(use-package powerthesaurus)
```

The installed version of Transient is `20230315.1520`.

Is there something I should change from my side?

Thanks.

**Comment by SavchenkoValeriy** [comment]
I reverted the change that introduced this bug, when Melpa builds `0.3.3`, it should fix the problem. Thanks again!

**Comment by nbarrientos** [comment]
Thank you, Valeriy.

**Comment by SavchenkoValeriy** [comment]
@nbarrientos It looks like Melpa has `0.3.3` ready, did it work?

**Comment by nbarrientos** [comment]
Yep, MELPA ships now `20230321.1459` which contains the revert.
