### ISSUE TITLE
Candidate selection breaks with Company mode

### ISSUE THREAD

**Issue by ntrocado** [SavchenkoValeriy/emacs-powerthesaurus#33]
While using company mode with the ispell backend, I followed these steps:
1. write "foo" and wait;
2. the company completion box appears;
3. call `M-x powerthesaurus-lookup-dwim RET RET RET`;
4. a candidate list will appear in the minibuffer, but it's not possible to use the arrow keys (or C-n C-p) to move the selection up or down. There's also a message: `funcall-interactively: Wrong type argument: number-or-marker-p, nil`.

**Comment by SavchenkoValeriy** [comment]
Oh wow, that's a very interesting case.
Thank you so much for taking your time and reporting it!

**Comment by SavchenkoValeriy** [comment]
Thanks for a detailed description, I managed to reproduce it and I believe I have a fix. Cheers!
