### ISSUE TITLE
error in process filter: powerthesaurus--preprocess-text:

### ISSUE THREAD

**Issue by djpeebles** [SavchenkoValeriy/emacs-powerthesaurus#34]
Hi,

I'm using powerthesaurus-20230321.1459 and have just attempted to replace a word with its synonym and received the following error messages:

```
error in process filter: powerthesaurus--preprocess-text: Symbol’s function definition is void: s-uppercase-p
error in process filter: Symbol’s function definition is void: s-uppercase-p
```
The word I was seeking to replace is deleted but the replacement word isn't inserted.

**Comment by SavchenkoValeriy** [comment]
I see, I think I removed `s.el` from (transitive) dependencies when I removed `request.el`.
And CI has dependencies cached, I guess. Anyways, before I fix it, you can install https://github.com/magnars/s.el and that should resolve this issue.

**Comment by SavchenkoValeriy** [comment]
And, of course, many thanks for taking your time to report it. I really appreciate it!

**Comment by djpeebles** [comment]
> And, of course, many thanks for taking your time to report it. I really appreciate it!

You're welcome!  Thank you for providing and maintaining the software!

**Comment by SavchenkoValeriy** [comment]
> Thanks for you reply. I've just checked and I already have s.el installed.

Can you please execute `(require 's)` and check one more time? If that won't work, would you mind checking what version of `s` do you have installed?
Thanks!

**Comment by djpeebles** [comment]
> > Thanks for you reply. I've just checked and I already have s.el installed.
> 
> Can you please execute `(require 's)` and check one more time? If that won't work, would you mind checking what version of `s` do you have installed? Thanks!

Done and the word replacement now works :-)  Just for your information, the version of s I'm using is s-20220902.1511

**Comment by SavchenkoValeriy** [comment]
Awesome, thanks for the confirmation. I'll make a proper fix when I get a free minute.

**Comment by djpeebles** [comment]
With the new update I now get the error

command-execute: Symbol’s value as variable is void: powerthesaurus-hydra

**Comment by SavchenkoValeriy** [comment]
@djpeebles thanks for reporting it.
I just can't get it right! I don't understand why it keeps happening. I am checking if `hydra` is available :-(

**Comment by SavchenkoValeriy** [comment]
@djpeebles Can you please create a new issue for this and describe the exact moment when this error happens? It can be also extremely useful if you can execute `toggle-debug-on-error` and share the backtrace. I can't seem to reproduce the issue locally.
